# Site settings
title: getBounds
header-img: img/header-2.png
email: malcolmtmeyer@gmail.com
description: "A (Jekyll) Blog Exploring Web Maps & Cartography."
baseurl: "http://getbounds.com"
testurl: "http://reyemtm.github.io"
url: "http://getbounds.com"
twitter_username: rustyfolk
github_username:  reyemtm
google+_usename: malcolmmeyer
facebook_username:
linkedin_username:	malcolm-meyer/44/2a2/577
author: Malcolm Meyer

# Build settings
markdown:	kramdown
highlighter: pygments
permalink: /:title.html
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
